In [1]:
import pandas as pd
import numpy as np

# Winning a Game

In [33]:
df = pd.read_csv('Wii Tennis Stats Final Project - Probability of Winning a Game.csv').set_index('Unnamed: 0')

In [34]:
df.iloc[-5, -5] = 0
df.iloc[-8, -7] = 0

In [35]:
df

00-00  00-15  15-00  15-15  30-0  0-30  30-15  15-30  30-30  \
Unnamed: 0                                                                 
00-00            0   0.35   0.65   0.00  0.00  0.00   0.00   0.00   0.00   
00-15            0   0.00   0.00   0.65  0.00  0.35   0.00   0.00   0.00   
15-00            0   0.00   0.00   0.35  0.65  0.00   0.00   0.00   0.00   
15-15            0   0.00   0.00   0.00  0.00  0.00   0.65   0.35   0.00   
30-0             0   0.00   0.00   0.00  0.00  0.00   0.35   0.00   0.00   
0-30             0   0.00   0.00   0.00  0.00  0.00   0.00   0.65   0.00   
30-15            0   0.00   0.00   0.00  0.00  0.00   0.00   0.00   0.35   
15-30            0   0.00   0.00   0.00  0.00  0.00   0.00   0.00   0.65   
30-30            0   0.00   0.00   0.00  0.00  0.00   0.00   0.00   0.00   
40-0             0   0.00   0.00   0.00  0.00  0.00   0.00   0.00   0.00   
0-40             0   0.00   0.00   0.00  0.00  0.00   0.00   0.00   0.00   
40-15            0   0.00   0.00   0.00  0.00  0.00   0.00   0.00   0.00   
15-40            0   0.00   0.00   0.00  0.00  0.00   0.00   0.00   0.00   
40-30            0   0.00   0.00   0.00  0.00  0.00   0.00   0.00   0.00   
30-40            0   0.00   0.00   0.00  0.00  0.00   0.00   0.00   0.00   
40-40/deuce      0   0.00   0.00   0.00  0.00  0.00   0.00   0.00   0.00   
40-Adv.          0   0.00   0.00   0.00  0.00  0.00   0.00   0.00   0.00   
Adv.-40          0   0.00   0.00   0.00  0.00  0.00   0.00   0.00   0.00   
WE WIN           0   0.00   0.00   0.00  0.00  0.00   0.00   0.00   0.00   
MATT WIN         0   0.00   0.00   0.00  0.00  0.00   0.00   0.00   0.00   

             40-0  0-40  40-15  15-40  40-30  30-40  40-40/deuce  40-Adv.  \
Unnamed: 0                                                                  
00-00        0.00  0.00   0.00   0.00   0.00   0.00         0.00     0.00   
00-15        0.00  0.00   0.00   0.00   0.00   0.00         0.00     0.00   
15-00        0.00  0.00   0.00   0.00   0.00   0.00         0.00     0.00   
15-15        0.00  0.00   0.00   0.00   0.00   0.00         0.00     0.00   
30-0         0.65  0.00   0.00   0.00   0.00   0.00         0.00     0.00   
0-30         0.00  0.35   0.00   0.00   0.00   0.00         0.00     0.00   
30-15        0.00  0.00   0.65   0.00   0.00   0.00         0.00     0.00   
15-30        0.00  0.00   0.00   0.35   0.00   0.00         0.00     0.00   
30-30        0.00  0.00   0.00   0.00   0.65   0.35         0.00     0.00   
40-0         0.00  0.00   0.35   0.00   0.00   0.00         0.00     0.00   
0-40         0.00  0.00   0.00   0.65   0.00   0.00         0.00     0.00   
40-15        0.00  0.00   0.00   0.00   0.35   0.00         0.00     0.00   
15-40        0.00  0.00   0.00   0.00   0.00   0.65         0.00     0.00   
40-30        0.00  0.00   0.00   0.00   0.00   0.00         0.35     0.00   
30-40        0.00  0.00   0.00   0.00   0.00   0.00         0.65     0.00   
40-40/deuce  0.00  0.00   0.00   0.00   0.00   0.00         0.00     0.35   
40-Adv.      0.00  0.00   0.00   0.00   0.00   0.00         0.65     0.00   
Adv.-40      0.00  0.00   0.00   0.00   0.00   0.00         0.35     0.00   
WE WIN       0.00  0.00   0.00   0.00   0.00   0.00         0.00     0.00   
MATT WIN     0.00  0.00   0.00   0.00   0.00   0.00         0.00     0.00   

             Adv.-40  WE WIN  MATT WIN  
Unnamed: 0                              
00-00           0.00    0.00      0.00  
00-15           0.00    0.00      0.00  
15-00           0.00    0.00      0.00  
15-15           0.00    0.00      0.00  
30-0            0.00    0.00      0.00  
0-30            0.00    0.00      0.00  
30-15           0.00    0.00      0.00  
15-30           0.00    0.00      0.00  
30-30           0.00    0.00      0.00  
40-0            0.00    0.65      0.00  
0-40            0.00    0.00      0.35  
40-15           0.00    0.65      0.00  
15-40           0.00    0.00      0.35  
40-30           0.00    0.65  

In [36]:
t = df.values
t.shape

(20, 20)

In [37]:
q = t[:18, :18]
q.shape

(18, 18)

In [44]:
r = t[:18, 18:]
r.shape

(18, 2)

In [39]:
q

array([[0.  , 0.35, 0.65, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.65, 0.  , 0.35, 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.35, 0.65, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.65, 0.35, 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.35, 0.  , 0.  , 0.65, 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.65, 0.  , 0.  , 0.35,
        0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.35, 0.  , 0.  ,
        0.65, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.65, 0.  , 0.  ,
        0.  , 0.35, 0.  , 0.  , 0.  , 0.  , 0.  ],


In [40]:
i = np.identity(18)
i

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0

In [41]:
i - q

array([[ 1.  , -0.35, -0.65,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , -0.65,  0.  , -0.35,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  , -0.35, -0.65,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  , -0.65, -0.35,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  1.  ,  0.  , -0.35,  0.  ,  0.  ,
        -0.65,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  1.  ,  0.  , -0.65,  0.  ,
         0.  , -0.35,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  1.  ,  0.  , -0.35,
         0.  ,  0.  , -0.65,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],

In [42]:
n = np.linalg.inv(i-q)
n

array([[1.        , 0.35      , 0.65      , 0.455     , 0.4225    ,
        0.1225    , 0.443625  , 0.238875  , 0.3105375 , 0.274625  ,
        0.042875  , 0.384475  , 0.111475  , 0.33641562, 0.18114687,
        0.43209346, 0.15123271, 0.28086075],
       [0.        , 1.        , 0.        , 0.65      , 0.        ,
        0.35      , 0.4225    , 0.455     , 0.443625  , 0.        ,
        0.1225    , 0.274625  , 0.238875  , 0.384475  , 0.3105375 ,
        0.61727638, 0.21604673, 0.40122964],
       [0.        , 0.        , 1.        , 0.35      , 0.65      ,
        0.        , 0.455     , 0.1225    , 0.238875  , 0.4225    ,
        0.        , 0.443625  , 0.042875  , 0.3105375 , 0.111475  ,
        0.33237959, 0.11633286, 0.21604673],
       [0.        , 0.        , 0.        , 1.        , 0.        ,
        0.        , 0.65      , 0.35      , 0.455     , 0.        ,
        0.        , 0.4225    , 0.1225    , 0.443625  , 0.238875  ,
        0.56979358, 0.19942775, 0.37036583],
    

In [43]:
n.shape

(18, 18)

In [46]:
nr = n @ r
df_final = pd.DataFrame(nr)
df_final

0         1
0   0.829645  0.170355
1   0.689214  0.310786
2   0.905261  0.094739
3   0.803719  0.196281
4   0.959937  0.040063
5   0.476563  0.523437
6   0.903433  0.096567
7   0.618536  0.381464
8   0.775229  0.224771
9   0.990363  0.009637
10  0.212897  0.787103
11  0.972466  0.027534
12  0.327534  0.672466
13  0.921330  0.078670
14  0.503899  0.496101
15  0.775229  0.224771
16  0.503899  0.496101
17  0.921330  0.078670

# Winning a Set

In [49]:
df = pd.read_csv('Wii Tennis Stats Final Project - Probability of Winning a Set.csv').set_index('Unnamed: 0').fillna(0)


In [50]:
df

0-0     0-1     0-2     0-3     0-4     0-5     1-0     1-1  \
Unnamed: 0                                                                
0-0           0  0.1704  0.0000  0.0000  0.0000  0.0000  0.8296  0.0000   
0-1           0  0.0000  0.1704  0.0000  0.0000  0.0000  0.0000  0.8296   
0-2           0  0.0000  0.0000  0.1704  0.0000  0.0000  0.0000  0.0000   
0-3           0  0.0000  0.0000  0.0000  0.1704  0.0000  0.0000  0.0000   
0-4           0  0.0000  0.0000  0.0000  0.0000  0.1704  0.0000  0.0000   
0-5           0  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
1-0           0  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.1704   
1-1           0  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
1-2           0  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
1-3           0  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
1-4           0  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
1-5           0  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
2-0           0  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
2-1           0  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
2-2           0  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
2-3           0  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
2-4           0  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
2-5           0  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
3-0           0  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
3-1           0  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
3-2           0  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
3-3           0  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
3-4           0  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
3-5           0  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
4-0           0  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
4-1           0  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
4-2           0  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
4-3           0  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
4-4           0  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
4-5           0  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
5-0           0  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
5-1           0  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
5-2           0  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
5-3           0  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
5-4           0  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
5-5           0  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
5-6           0  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
6-5           0  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
6-6           0  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
Adv. Us       0  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
Adv. Matt     0  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
WE WIN        0  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
MATT WIN      0  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   

               1-2     1-3  ...     5-3     5-4     5-5     5-6     6-5  \
Unnamed: 0                  ...                                           
0-0         0.0000  0.0000  ...  0.0000  0.0000  0.0000  0.0000  0.0000   
0-1         0.0000  0.0000  ...  0.0000  0.0000  0.0000  0.0000  0.0000   
0-2         0.8296  0.0000  ...  0.0000  0.0000  0.0000  0.0000  0.0000   
0-3         0.0000  0.8296  ...  0.0000  0.0000  0.0000  0.0000  0.0000   
0-4         0.0000  0.0000  ...  0.0000  0.0000  0.0000  0.0000  0.0000   
0-5         0.0000  0.0000  ...  0.0000  0.0000  0.0000  0.0000  0.0000   
1-0         0.0000  0.0000  ...  0.0

In [51]:
t = df.values
t.shape

(43, 43)

In [54]:
q = t[:41, :41]
q.shape

(41, 41)

In [55]:
r = t[:41, 41:]
r.shape

(41, 2)

In [56]:
i = np.identity(41)
i.shape

(41, 41)

In [58]:
n = np.linalg.inv(i-q)
n.shape

(41, 41)

In [59]:
nr = n @ r
df_final = pd.DataFrame(nr)
df_final

0         1
0   0.996626  0.003255
1   0.988135  0.011165
2   0.960679  0.035217
3   0.878255  0.097656
4   0.647241  0.211395
5   0.000000  0.170400
6   0.998370  0.001630
7   0.993775  0.006225
8   0.977609  0.022391
9   0.925706  0.074294
10  0.780185  0.219815
11  0.454494  0.545506
12  0.999314  0.000686
13  0.997095  0.002905
14  0.988269  0.011731
15  0.955596  0.044404
16  0.847082  0.152918
17  0.547847  0.452153
18  0.999770  0.000230
19  0.998908  0.001092
20  0.994981  0.005019
21  0.977884  0.022116
22  0.908545  0.091455
23  0.660375  0.339625
24  0.999947  0.000053
25  0.999715  0.000285
26  0.998492  0.001508
27  0.992127  0.007873
28  0.959519  0.040481
29  0.796017  0.203983
30  0.999994  0.000006
31  0.999966  0.000034
32  0.999800  0.000200
33  0.998825  0.001175
34  0.993102  0.006898
35  0.959519  0.040481
36  0.796017  0.203983
37  0.993102  0.006898
38  0.959519  0.040481
39  0.993102  0.006898
40  0.796017  0.203983